---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  tasks:
    - name: Remove incorrect localhost entries from /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^(127\.0\.0\.1|::1)\s+{{ freeipa_fqdn }}\s+(.*)$'
        state: absent

    - name: Update /etc/hosts with correct entries
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED - CORRECT ENTRY FOR {{ freeipa_fqdn }}"
        block: |
          {{ ansible_host }} {{ freeipa_fqdn }}

    - name: Install and configure FreeIpa server
      ansible.builtin.include_role:
        name: freeipa.ansible_freeipa.ipaserver
